### ISSUE TITLE
org.globaltester.parent Version 3.8.3-SNAPSHOT is missing

### ISSUE THREAD

**Issue by markuskreusch** [GlobalTester/org.globaltester.parent#1]
Some of the repositories in the context of persosim reference org.globaltester.parent:org.globaltester.parent:3.8.3-SNAPSHOT. This version is not available here. Where is it?

The relevant projects are:
- de.persosim:de.persosim.driver.connector:0.18.3-SNAPSHOT
- de.persosim:de.persosim.driver.connector.test:0.18.3-SNAPSHOT
- de.persosim:de.persosim.driver.connector.ui:0.18.3-SNAPSHOT
- de.persosim:de.persosim.editor.rcp:0.18.3-SNAPSHOT
- de.persosim:de.persosim.editor.rcp.feature:0.18.3-SNAPSHOT
- de.persosim:de.persosim.editor.rcp.product:0.18.3-SNAPSHOT
- de.persosim:de.persosim.editor.ui:0.18.3-SNAPSHOT
- de.persosim:de.persosim.rcp:0.18.3-SNAPSHOT
- de.persosim:de.persosim.rcp.coverage:0.18.3-SNAPSHOT
- de.persosim:de.persosim.rcp.feature:0.18.3-SNAPSHOT
- de.persosim:de.persosim.rcp.product:0.18.3-SNAPSHOT
- de.persosim:de.persosim.remoteifd:0.18.3-SNAPSHOT
- de.persosim:de.persosim.remoteifd.test:0.18.3-SNAPSHOT
- de.persosim:de.persosim.remoteifd.ui:0.18.3-SNAPSHOT
- de.persosim:de.persosim.simulator:0.18.3-SNAPSHOT
- de.persosim:de.persosim.simulator.adapter.socket:0.18.3-SNAPSHOT
- de.persosim:de.persosim.simulator.integrationtest:0.18.3-SNAPSHOT
- de.persosim:de.persosim.simulator.test:0.18.3-SNAPSHOT
- de.persosim:de.persosim.simulator.ui:0.18.3-SNAPSHOT

**Comment by halemmerich** [comment]
[PersoSim](https://github.com/PersoSim) has forks of the relevant repositories. They contain the required versions.
